apiVersion: v1
kind: Service
metadata:
  name: atlas-billing
  namespace: atlas-production
  labels:
    app: atlas-billing
spec:
  type: ClusterIP
  selector:
    app: atlas-billing
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
